repos:
- repo: "local"
  hooks:
  - id: "format-julia"
    name: "Format with JuliaFormatter"
    entry: "julia --project helper_scripts/format_julia_files.jl"
    language: "system"

  - id: "build-notebooks"
    name: "Build Notebooks"
    language: "script"
    entry: "./helper_scripts/build_notebooks.sh"
    files: 'examples/src/\.jl$'

